In [45]:
import matplotlib.pyplot as plt
import pandas as pd 
stories = pd.read_excel('../data/stories_cleaned.xlsx')
heroines = pd.read_excel('../data/candidates_cleaned.xlsx')
df = pd.merge(heroines, stories, on="story_id")

In [46]:
ml_df = df.drop(columns=[
    "candidate_id",
    "candidate_name",
    "confidence_score",
    "reasoning",
    "commitment_status",
    "first_chapter_or_episode",
    "confidence_score"

])

In [47]:
stories["heroine_count"].mean()
#Heroine count greater than the dataset mean (4.43).
#Stories with more heroines than the dataset average may distribute romantic focus 
# across more characters, reducing the probability of any single heroine winning

np.float64(4.426470588235294)

High Heroine Count

In [48]:
mean_heroine = stories["heroine_count"].mean()
ml_df["high_heroine_count"] = (
    ml_df["heroine_count"] > mean_heroine
).astype(int)

In [49]:
ml_df["high_heroine_count"]

0      1
1      1
2      1
3      1
4      1
      ..
296    0
297    0
298    0
299    0
300    0
Name: high_heroine_count, Length: 301, dtype: int64

introduced early

In [50]:
ml_df["introduced_early"] = (
    ml_df["introduction_order"] <= 3
).astype(int)

childhood friend

In [51]:
ml_df["has_childhood_connection"] = (
    ml_df["childhood_connection"].isin(["Childhood Friend", 
        "Childhood Promise",
        "Acquaintance"
    ])
).astype(int)

In [52]:
# if modern series
ml_df["is_modern"] = (
    ml_df["release_year"] >= 2010
).astype(int)

In [53]:
ml_df[[
    "heroine_count",
    "high_heroine_count",
    "introduction_order",
    "introduced_early",
    "childhood_connection",
    "has_childhood_connection",
    "release_year",
    "is_modern"
]].head(10)

,heroine_count,high_heroine_count,introduction_order,introduced_early,childhood_connection,has_childhood_connection,release_year,is_modern
0,5,1,1,1,Childhood Promise,1,2011,1
1,5,1,2,1,Childhood Promise,1,2011,1
2,5,1,3,1,NaN,0,2011,1
3,5,1,4,0,Childhood Promise,1,2011,1
4,5,1,5,0,NaN,0,2011,1
5,5,1,1,1,NaN,0,2017,1
6,5,1,2,1,NaN,0,2017,1
7,5,1,3,1,NaN,0,2017,1
8,5,1,4,0,Childhood Promise,1,2017,1
9,5,1,5,0,NaN,0,2017,1

One-Hot Encoding

hair color

In [54]:
encoded_df = pd.get_dummies(ml_df[["hair_color", 
"primary_archetype",
'hair_color',
"medium",
"target_audience",
"demographic",
"setting",
"romance_type"
]])
print(encoded_df)

     hair_color_Black  hair_color_Blonde  hair_color_Blue  hair_color_Brown  \
0               False               True            False             False
1                True              False            False             False
2               False              False             True             False
3               False              False            False             False
4                True              False            False             False
..                ...                ...              ...               ...
296              True              False            False             False
297             False              False            False              True
298             False              False            False             False
299             False              False             True             False
300              True              False            False             False

     hair_color_Green  hair_color_Orange  hair_color_Pink  hair_color_Purple  \
0               False              False            False              False
1               False              False            False              False
2               False              False            False              False
3               False               True            False              False
4               False              False            False              False
..                ...                ...              ...                ...
296             False              False            False              False
297             False              False            False              False
298             False              False            False               True
299             False              False            False              False
300             False              False            False              False

     hair_color_Red  hair_color_Silver  ...  romance_type_Harem  \
0             False              False  ...                True
1             False              False  ...                True
2             False              False  ...                True
3             False              False  ...                True
4             False              False  ...                True
..              ...                ...  ...                 ...
296           False              False  ...               False
297           False              False  ...               False
298           False              False  ...               False
299           False              False  ...               False
300           False              False  ...               False

     romance_type_Love Triangle  romance_type_Love Triangle/Harem  \
0                         False                             False
1                         False                             False
2                         False                             False
3                         False                             False
4                         False                             False
..                          ...                               ...
296                       False                             False
297                        True                             False
298                        True                             False
299                        True                             False
300                        True                             False

     romance_type_Multiple Romance Candidates  romance_type_Reverse Harem  \
0                                       False                       False
1                                       False                       False
2                                       False                       False
3                                       False                       False
4                                       False                       False
..                                        ...                         ...
296                                     False                       False
297                                     False                       False
298                                     False                       False
299                                     False                       False
300                                     False                       False

     romance_type_Romance Pairing  romance_type_Romance/Harem  \
0                           False                       False
1                           False                       False
2                           False                       False
3                           False                       False
4                           False                       False
..                            ...                         ...
296                          True                       False
297                         False                       False
298                         False                       False
299                         False                       False
300                         False                       False

     romance_type_Romantic Comedy  romance_type_Romantic Rivalry  \
0                           False                          False
1                           False                          False
2                           False                          False
3                           False                          False
4                           False                          False
..                            ...                            ...
296                         False                          False
297                         False                          False
298                         False                          False
299                         False                          False
300                         False                          False

     romance_type_Single Romance
0                          False
1                          False
2                          False
3                          False
4                          False
..                           ...
296                        False
297                        False
298                        False
299                        False
300                        False

[301 rows x 74 columns]

In [55]:
ml_df.columns

Index(['story_id', 'candidate_gender', 'won', 'first_girl',
       'introduction_order', 'childhood_connection', 'primary_archetype',
       'hair_color', 'appearance_order', 'favorites', 'story_favorites_rank',
       'title', 'medium', 'release_year', 'status', 'author',
       'target_audience', 'demographic', 'setting', 'romance_type',
       'heroine_count', 'source_material', 'mal_id', 'mal_score',
       'mal_popularity', 'mal_members', 'mal_favorites', 'mal_genres',
       'mal_themes', 'serialization', 'high_heroine_count', 'introduced_early',
       'has_childhood_connection', 'is_modern'],
      dtype='str')

In [ ]:

ml_df.drop(columns=["story_id",
"title",
"status",
"author",
"source_material",
"mal_id",
"mal_genres",
"mal_themes",
"serialization",
"childhood_connection",
"candidate_gender",
"primary_archetype",
"hair_color",
"medium",
"target_audience",
"demographic",
"setting",
"romance_type"])

,won,first_girl,introduction_order,primary_archetype,hair_color,appearance_order,favorites,story_favorites_rank,medium,release_year,...,romance_type,heroine_count,mal_score,mal_popularity,mal_members,mal_favorites,high_heroine_count,introduced_early,has_childhood_connection,is_modern
0,1,1,1,Tsundere,Blonde,1,11305,1,Manga,2011,...,Harem,5,7.72,45,210467,13517,1,1,1,1
1,0,0,2,Deredere,Black,1,7715,2,Manga,2011,...,Harem,5,7.72,45,210467,13517,1,1,1,1
2,0,0,3,Tsundere,Blue,2,1472,3,Manga,2011,...,Harem,5,7.72,45,210467,13517,1,1,0,1
3,0,0,4,Deredere,Orange,3,809,4,Manga,2011,...,Harem,5,7.72,45,210467,13517,1,0,1,1
4,0,0,5,Deredere,Black,4,90,5,Manga,2011,...,Harem,5,7.72,45,210467,13517,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,1,1,1,Kuudere,Black,1,443,1,Manga,2012,...,Romance Pairing,1,7.93,850,26073,535,0,1,0,1
297,0,1,1,Genki,Brown,1,53,2,Anime,2007,...,Love Triangle,4,7.10,1455,193129,773,0,1,1,0
298,1,0,2,Dandere,Purple,1,164,1,Anime,2007,...,Love Triangle,4,7.10,1455,193129,773,0,1,1,0
299,0,0,3,Tsundere,Blue,1,18,4,Anime,2007,...,Love Triangle,4,7.10,1455,193129,773,0,1,1,0
300,0,0,4,Deredere,Black,1,30,3,Anime,2007,...,Love Triangle,4,7.10,1455,193129,773,0,0,0,0